#!/usr/bin/env python3
"""Render the fork's identity artifacts from fork-identity.json.

Driven by scripts/inject-fork-identity.sh; kept separate so the rendering is
plain readable Python rather than quoting-sensitive shell.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

XCCONFIG_TEMPLATE = """\
// GENERATED by scripts/inject-fork-identity.sh -- do not edit by hand.
// Source of truth: fork-identity.json (channel: {channel})
//
// Consumed two ways, so CLI and Xcode.app builds resolve identical values:
//   * as the project-level baseConfigurationReference in cmux.xcodeproj
//   * via `xcodebuild -xcconfig` from scripts/reload.sh
//
// The Xcode project references these as $(CMUX_FORK_*) rather than hardcoding fork
// identity, which holds the project file's fork diff to a fixed handful of
// lines that upstream rebases do not touch.

CMUX_FORK_SLASH = /

CMUX_FORK_CHANNEL = {channel}
CMUX_FORK_APP_NAME = {app_name}
CMUX_FORK_BUNDLE_ID = {bundle_id}
CMUX_FORK_BUNDLE_ID_TESTS = {bundle_id}.tests
CMUX_FORK_BUNDLE_ID_UITESTS = {bundle_id}.uitests
CMUX_FORK_URL_SCHEME = {url_scheme}
CMUX_FORK_APP_ICON_NAME = {app_icon}
CMUX_FORK_SPARKLE_FEED_URL = {sparkle_feed_escaped}
CMUX_FORK_TEAM_ID = {team_id}
CMUX_FORK_REPO = {repo}
"""

ENV_TEMPLATE = """\
# GENERATED by scripts/inject-fork-identity.sh -- do not edit by hand.
# Source of truth: fork-identity.json (channel: {channel})
# Shell: `source scripts/fork-identity.env`
# Python: read fork-identity.json directly rather than parsing this file.
CMUX_FORK_CHANNEL="{channel}"
CMUX_FORK_APP_NAME="{app_name}"
CMUX_FORK_BUNDLE_ID="{bundle_id}"
CMUX_FORK_BUNDLE_ID_TESTS="{bundle_id}.tests"
CMUX_FORK_BUNDLE_ID_UITESTS="{bundle_id}.uitests"
CMUX_FORK_URL_SCHEME="{url_scheme}"
CMUX_FORK_APP_ICON_NAME="{app_icon}"
CMUX_FORK_SPARKLE_FEED_URL="{sparkle_feed}"
CMUX_FORK_TEAM_ID="{team_id}"
CMUX_FORK_SIGNING_CERT="{signing_cert}"
CMUX_FORK_NOTARY_PROFILE="{notary_profile}"
CMUX_FORK_REPO="{repo}"
CMUX_UPSTREAM_REPO="{upstream_repo}"
"""


def escape_for_xcconfig(url: str) -> str:
    """Protect a URL's `//` from xcconfig's comment syntax.

    xcconfig treats `//` as the start of a comment anywhere on a line, which
    would truncate `https://host/path` to `https:`. Rebuilding the separator
    from a single-slash variable is the standard workaround: the emitted text
    holds one literal slash plus one expanded slash, so no literal `//` ever
    appears in the source and the resolved value still has exactly two.
    """
    return url.replace("//", "/${CMUX_FORK_SLASH}", 1)


def build_fields(data: dict, channel: str) -> dict:
    channels = data["channels"]
    if channel not in channels:
        raise SystemExit(
            f"error: unknown channel {channel!r}; "
            f"expected one of {', '.join(sorted(channels))}"
        )

    entry = channels[channel]
    signing = data["signing"]
    repo = data["repo"]

    return {
        "channel": channel,
        "app_name": entry["app_name"],
        "bundle_id": entry["bundle_id"],
        "url_scheme": entry["url_scheme"],
        "app_icon": entry["app_icon"],
        "sparkle_feed": entry["sparkle_feed"],
        "sparkle_feed_escaped": escape_for_xcconfig(entry["sparkle_feed"]),
        "team_id": signing["team_id"],
        "signing_cert": signing["developer_id_cert"],
        "notary_profile": signing["notary_profile"],
        "repo": f"{repo['owner']}/{repo['name']}",
        "upstream_repo": data["upstream"]["repo"],
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument("--channel", default="stable")
    parser.add_argument("--xcconfig", type=Path)
    parser.add_argument("--env", type=Path)
    parser.add_argument(
        "--print",
        dest="print_key",
        choices=["upstream_bundle_id", "bundle_id", "app_name"],
        help="Print one value and exit, for shell callers.",
    )
    args = parser.parse_args()

    data = json.loads(args.source.read_text())

    if args.print_key == "upstream_bundle_id":
        print(data["upstream"]["bundle_id"])
        return 0

    fields = build_fields(data, args.channel)

    if args.print_key:
        print(fields[args.print_key])
        return 0

    if not args.xcconfig or not args.env:
        parser.error("--xcconfig and --env are required unless --print is used")

    args.xcconfig.parent.mkdir(parents=True, exist_ok=True)
    args.env.parent.mkdir(parents=True, exist_ok=True)
    args.xcconfig.write_text(XCCONFIG_TEMPLATE.format(**fields))
    args.env.write_text(ENV_TEMPLATE.format(**fields))
    return 0


if __name__ == "__main__":
    sys.exit(main())
